import { NextResponse } from "next/server";

const berita = [
  {
    id: 1,
    title: "Peluncuran Portal Data Terbuka Kota Serang",
    excerpt: "Pemerintah Kota Serang meluncurkan portal data terbuka untuk meningkatkan transparansi.",
    image: "/assets/kota-serang.png",
    date: "01 Sep 2025",
  },
  {
    id: 2,
    title: "Statistik Penduduk Kota Serang 2025",
    excerpt: "Jumlah penduduk Kota Serang tahun 2025 mengalami peningkatan dibanding tahun sebelumnya.",
    image: "/assets/kota-serang.png",
    date: "30 Agu 2025",
  },
  {
    id: 2,
    title: "Pengumuman Pemeliharaan Sistem Data",
    excerpt: "Akan dilakukan pemeliharaan rutin pada sistem portal data Kota Serang.",
    image: "/assets/kota-serang.png",
    date: "28 Agu 2025",
  },
  {
    id: 2,
    title: "Data UMKM Kota Serang Diperbarui",
    excerpt: "Pembaruan data UMKM Kota Serang kini dapat diakses oleh publik.",
    image: "/assets/kota-serang.png",
    date: "25 Agu 2025",
  },
  {
    id: 2,
    title: "Rilis Data Pendidikan Terbaru",
    excerpt: "Data sekolah, guru, dan murid Kota Serang telah diperbarui hingga tahun 2025.",
    image: "/assets/kota-serang.png",
    date: "22 Agu 2025",
  },
  {
    id: 2,
    title: "Sosialisasi Pemanfaatan Data Terbuka",
    excerpt: "Pemkot Serang menggelar sosialisasi pentingnya data terbuka bagi masyarakat.",
    image: "/assets/kota-serang.png",
    date: "20 Agu 2025",
  },
  {
    id: 2,
    title: "Kunjungan Wisata di Kota Serang Meningkat",
    excerpt: "Jumlah wisatawan domestik dan mancanegara mengalami kenaikan signifikan.",
    image: "/assets/kota-serang.png",
    date: "18 Agu 2025",
  },
  {
    id: 2,
    title: "Data Kesehatan Kota Serang Diperbarui",
    excerpt: "Informasi fasilitas kesehatan, puskesmas, dan tenaga medis telah diperbaharui.",
    image: "/assets/kota-serang.png",
    date: "15 Agu 2025",
  },
  {
    id: 2,
    title: "Rapat Evaluasi Satudata Kota Serang",
    excerpt: "Evaluasi rutin dilakukan untuk meningkatkan kualitas portal Satudata.",
    image: "/assets/kota-serang.png",
    date: "12 Agu 2025",
  },
  {
    id: 2,
    title: "Data Anggaran Kota Serang 2025",
    excerpt: "APBD Kota Serang tahun 2025 kini tersedia dalam format terbuka.",
    image: "/assets/kota-serang.png",
    date: "10 Agu 2025",
  },
  {
    id: 2,
    title: "Pengumuman Lomba Inovasi Data",
    excerpt: "Pemkot Serang menggelar lomba inovasi pemanfaatan data terbuka.",
    image: "/assets/kota-serang.png",
    date: "08 Agu 2025",
  },
  {
    id: 2,
    title: "Bimtek Satudata untuk OPD",
    excerpt: "Pelatihan teknis untuk operator OPD terkait input data Satudata.",
    image: "/assets/kota-serang.png",
    date: "06 Agu 2025",
  },
  {
    id: 2,
    title: "Data Transportasi Kota Serang",
    excerpt: "Statistik kendaraan umum dan transportasi pribadi kini tersedia.",
    image: "/assets/kota-serang.png",
    date: "05 Agu 2025",
  },
  {
    id: 2,
    title: "Peringatan Hari Data Terbuka",
    excerpt: "Pemkot Serang ikut serta memperingati Hari Data Terbuka Nasional.",
    image: "/assets/kota-serang.png",
    date: "02 Agu 2025",
  },
  {
    id: 2,
    title: "Update Data Lingkungan Hidup",
    excerpt: "Informasi terbaru mengenai kualitas udara dan lingkungan Kota Serang.",
    image: "/assets/kota-serang.png",
    date: "30 Jul 2025",
  },
  {
    id: 2,
    title: "Launching Dashboard Statistik Interaktif",
    excerpt: "Dashboard interaktif kini tersedia untuk publik.",
    image: "/assets/kota-serang.png",
    date: "28 Jul 2025",
  },
  {
    id: 2,
    title: "Kerja Sama Data dengan Universitas",
    excerpt: "Pemkot Serang bekerja sama dengan perguruan tinggi untuk riset berbasis data.",
    image: "/assets/kota-serang.png",
    date: "25 Jul 2025",
  },
  {
    id: 2,
    title: "Rilis Data Energi Kota Serang",
    excerpt: "Statistik penggunaan listrik dan energi terbarukan telah dirilis.",
    image: "/assets/kota-serang.png",
    date: "22 Jul 2025",
  },
  {
    id: 2,
    title: "Peningkatan Kapasitas Server Satudata",
    excerpt: "Upgrade server dilakukan untuk meningkatkan performa portal.",
    image: "/assets/kota-serang.png",
    date: "20 Jul 2025",
  },
  {
    id: 2,
    title: "Pengumuman Libur Layanan Satudata",
    excerpt: "Layanan Satudata akan libur pada hari raya Idul Adha.",
    image: "/assets/kota-serang.png",
    date: "18 Jul 2025",
  },
];

export async function GET() {
  return NextResponse.json(berita);
}
